-- =========================
-- CASO 1 - COMO SYS/SYSTEM
-- =========================

CREATE USER PRY2205_EFT IDENTIFIED BY "CambiaESTA_12AAbb22"
  DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP
  QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_DES IDENTIFIED BY "CambiaESTA_12AAbb33"
  DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP
  QUOTA 10M ON DATA;

CREATE USER PRY2205_EFT_CON IDENTIFIED BY "CambiaESTA_12AAbb44"
  DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP
  QUOTA 10M ON DATA;

GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

-- =========================
-- CASO 1 - ROLES (SYS/ADMIN)
-- =========================
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;

ALTER USER PRY2205_EFT_DES DEFAULT ROLE PRY2205_ROL_D;
ALTER USER PRY2205_EFT_CON DEFAULT ROLE PRY2205_ROL_C;

-- =========================
-- PRIVILEGIOS PARA POBLAR ESQUEMA
-- =========================

GRANT CREATE TABLE TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;

-- =========================
-- CASO 1 - POBLADO DE DATOS (PRY2205_EFT)
-- =========================
--EJECUTAR CODIGO DE POBLADO
-- =========================
-- CASO 1 - GRANT DE LECTURA A ROLES (PRY2205_EFT)
-- =========================

-- Rol DES (más tablas)
GRANT SELECT ON COMUNA          TO PRY2205_ROL_D;
GRANT SELECT ON SECTOR          TO PRY2205_ROL_D;
GRANT SELECT ON PROFESION       TO PRY2205_ROL_D;
GRANT SELECT ON TIPO_CONTRATO   TO PRY2205_ROL_D;
GRANT SELECT ON RANGOS_SUELDOS  TO PRY2205_ROL_D;
GRANT SELECT ON AFP             TO PRY2205_ROL_D;
GRANT SELECT ON ISAPRE          TO PRY2205_ROL_D;
GRANT SELECT ON EMPRESA         TO PRY2205_ROL_D;
GRANT SELECT ON PROFESIONAL     TO PRY2205_ROL_D;

-- Rol CON (mínimo necesario)
GRANT SELECT ON COMUNA          TO PRY2205_ROL_C;
GRANT SELECT ON SECTOR          TO PRY2205_ROL_C;
GRANT SELECT ON PROFESION       TO PRY2205_ROL_C;
GRANT SELECT ON EMPRESA         TO PRY2205_ROL_C;
GRANT SELECT ON PROFESIONAL     TO PRY2205_ROL_C;

-- =========================
-- SINÓNIMOS PÚBLICOS
-- =========================

CREATE OR REPLACE PUBLIC SYNONYM S_COMUNA         FOR PRY2205_EFT.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM S_SECTOR         FOR PRY2205_EFT.SECTOR;
CREATE OR REPLACE PUBLIC SYNONYM S_PROFESION      FOR PRY2205_EFT.PROFESION;
CREATE OR REPLACE PUBLIC SYNONYM S_TIPO_CONTRATO  FOR PRY2205_EFT.TIPO_CONTRATO;
CREATE OR REPLACE PUBLIC SYNONYM S_RANGOS_SUELDOS FOR PRY2205_EFT.RANGOS_SUELDOS;
CREATE OR REPLACE PUBLIC SYNONYM S_AFP            FOR PRY2205_EFT.AFP;
CREATE OR REPLACE PUBLIC SYNONYM S_ISAPRE         FOR PRY2205_EFT.ISAPRE;
CREATE OR REPLACE PUBLIC SYNONYM S_EMPRESA        FOR PRY2205_EFT.EMPRESA;
CREATE OR REPLACE PUBLIC SYNONYM S_PROFESIONAL    FOR PRY2205_EFT.PROFESIONAL;



-- =========================
-- CASO 2 (PRY2205_EFT_DES)
-- =========================

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CARTOLA_PROFESIONALES';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/


CREATE TABLE CARTOLA_PROFESIONALES AS
SELECT
  p.RUTPROF AS RUT_PROFESIONAL,
  p.NOMPRO||' '||p.APPPRO||' '||p.APMPRO AS NOMBRE_PROFESIONAL,
  pr.NOMPROFESION AS PROFESION,
  i.NOMISAPRE AS ISAPRE,
  p.SUELDO AS SUELDO_BASE,
  NVL(p.COMISION,0) AS PORC_COMISION_PROFESION,
  ROUND(p.SUELDO*NVL(p.COMISION,0)) AS VALOR_TOTAL_COMISION,
  ROUND(p.SUELDO*NVL(r.HONOR_PCT,0)/100) AS PORCENTAJE_HONORARIO,
  CASE tc.NOMTCONTRATO
    WHEN 'Indefinido Jornada Completa' THEN 150000
    WHEN 'Indefinido Jornada Parcial' THEN 120000
    WHEN 'Plazo fijo' THEN 60000
    WHEN 'Honorarios' THEN 50000
    ELSE 0
  END AS BONO_MOVILIZACION,
  p.SUELDO
  + ROUND(p.SUELDO*NVL(p.COMISION,0))
  + ROUND(p.SUELDO*NVL(r.HONOR_PCT,0)/100)
  + CASE tc.NOMTCONTRATO
      WHEN 'Indefinido Jornada Completa' THEN 150000
      WHEN 'Indefinido Jornada Parcial' THEN 120000
      WHEN 'Plazo fijo' THEN 60000
      WHEN 'Honorarios' THEN 50000
      ELSE 0
    END AS TOTAL_PAGAR
FROM S_PROFESIONAL p
JOIN S_PROFESION pr ON p.IDPROFESION = pr.IDPROFESION
JOIN S_ISAPRE i ON p.IDISAPRE = i.IDISAPRE
JOIN S_TIPO_CONTRATO tc ON p.IDTCONTRATO = tc.IDTCONTRATO
LEFT JOIN S_RANGOS_SUELDOS r
  ON p.SUELDO BETWEEN r.S_MIN AND r.S_MAX
ORDER BY
  pr.NOMPROFESION,
  p.SUELDO DESC,
  NVL(p.COMISION,0),
  p.RUTPROF;



SELECT*FROM CARTOLA_PROFESIONALES;

GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_EFT_CON;

CREATE OR REPLACE PUBLIC SYNONYM S_CARTOLA_PROFESIONALES
FOR PRY2205_EFT_DES.CARTOLA_PROFESIONALES;


-- =========================
-- CASO 2 - TEST (PRY2205_EFT_CON)
-- =========================

SELECT * FROM S_CARTOLA_PROFESIONALES;

-- =========================
-- CASO 3.1 - CREACIÓN DE LA VISTA (PRY2205_EFT)
-- =========================
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
  SUBSTR(LPAD(e.RUT_EMPRESA,8,'0'),1,2)||'.'||
  SUBSTR(LPAD(e.RUT_EMPRESA,8,'0'),3,3)||'.'||
  SUBSTR(LPAD(e.RUT_EMPRESA,8,'0'),6,3)||'-'||e.DV_EMPRESA AS RUT_EMPRESA,
  UPPER(e.NOMEMPRESA) AS NOMBRE_EMPRESA,
  e.IVA_DECLARADO AS IVA,
  EXTRACT(YEAR FROM SYSDATE)
   - EXTRACT(YEAR FROM e.FECHA_INICIACION_ACTIVIDADES) AS ANIOS_EXISTENCIA,
  ROUND(COUNT(a.IDEMPRESA)/12,0) AS TOTAL_ASESORIAS_ANUALES,
  ROUND(e.IVA_DECLARADO*(COUNT(a.IDEMPRESA)/12)/100) AS DEVOLUCION_IVA,
  CASE
    WHEN COUNT(a.IDEMPRESA)/12>5 THEN 'CLIENTE PREMIUM'
    WHEN COUNT(a.IDEMPRESA)/12 BETWEEN 3 AND 5 THEN 'CLIENTE'
    ELSE 'CLIENTE POCO CONCURRIDO'
  END AS TIPO_CLIENTE,
  CASE
    WHEN COUNT(a.IDEMPRESA)/12>5 THEN '1 ASESORIA GRATIS'
    ELSE 'CAPTAR CLIENTE'
  END AS CORRESPONDE
FROM EMPRESA e
JOIN ASESORIA a ON e.IDEMPRESA=a.IDEMPRESA
WHERE EXTRACT(YEAR FROM a.FIN)=EXTRACT(YEAR FROM SYSDATE)-1
GROUP BY
  e.RUT_EMPRESA,
  e.DV_EMPRESA,
  e.NOMEMPRESA,
  e.FECHA_INICIACION_ACTIVIDADES,
  e.IVA_DECLARADO
ORDER BY
  UPPER(e.NOMEMPRESA);


SELECT*FROM VW_EMPRESAS_ASESORADAS;

GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;
CREATE OR REPLACE PUBLIC SYNONYM S_VW_EMPRESAS_ASESORADAS
FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

-- =========================
-- CASO 3.1 - TEST (PRY2205_EFT_CON)
-- =========================
SELECT * FROM S_VW_EMPRESAS_ASESORADAS;


-- =========================
-- CASO 3.2
-- =========================
EXPLAIN PLAN FOR SELECT * FROM VW_EMPRESAS_ASESORADAS; 
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 CREATE INDEX IDX_ASESORIA_EMPRESA_FIN ON ASESORIA(IDEMPRESA,FIN); 
 CREATE INDEX IDX_EMPRESA_ID ON EMPRESA(IDEMPRESA); 
 EXPLAIN PLAN FOR SELECT * FROM VW_EMPRESAS_ASESORADAS;
  SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);



